# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/wyrdmeister/Docs_UniMi/SoftProjects/ATMD-GPX/atmd-server/atmd-gui/ui/mainwindow.ui'
#
# Created: Wed Apr 25 20:26:17 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(571, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "ATMD-GPX Control", None, QtGui.QApplication.UnicodeUTF8))
        self.centralWidget = QtGui.QWidget(mainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.server_address = QtGui.QLineEdit(self.centralWidget)
        self.server_address.setGeometry(QtCore.QRect(20, 30, 131, 27))
        self.server_address.setText(QtGui.QApplication.translate("mainWindow", "192.168.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.server_address.setObjectName(_fromUtf8("server_address"))
        self.connect_button = QtGui.QPushButton(self.centralWidget)
        self.connect_button.setGeometry(QtCore.QRect(250, 30, 100, 27))
        self.connect_button.setText(QtGui.QApplication.translate("mainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.connect_button.setObjectName(_fromUtf8("connect_button"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 67, 17))
        self.label.setText(QtGui.QApplication.translate("mainWindow", "Server:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.measure_time = QtGui.QLineEdit(self.centralWidget)
        self.measure_time.setGeometry(QtCore.QRect(130, 86, 141, 27))
        self.measure_time.setText(_fromUtf8(""))
        self.measure_time.setObjectName(_fromUtf8("measure_time"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(26, 91, 101, 17))
        self.label_2.setText(QtGui.QApplication.translate("mainWindow", "Measure time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.window_time = QtGui.QLineEdit(self.centralWidget)
        self.window_time.setGeometry(QtCore.QRect(130, 126, 141, 27))
        self.window_time.setText(_fromUtf8(""))
        self.window_time.setObjectName(_fromUtf8("window_time"))
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(29, 131, 101, 17))
        self.label_3.setText(QtGui.QApplication.translate("mainWindow", "Window time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.deadtime = QtGui.QLineEdit(self.centralWidget)
        self.deadtime.setGeometry(QtCore.QRect(130, 166, 141, 27))
        self.deadtime.setText(_fromUtf8(""))
        self.deadtime.setObjectName(_fromUtf8("deadtime"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(52, 171, 81, 17))
        self.label_4.setText(QtGui.QApplication.translate("mainWindow", "Deadtime:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.save_prefix = QtGui.QLineEdit(self.centralWidget)
        self.save_prefix.setGeometry(QtCore.QRect(130, 206, 141, 27))
        self.save_prefix.setText(_fromUtf8(""))
        self.save_prefix.setObjectName(_fromUtf8("save_prefix"))
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(44, 211, 81, 16))
        self.label_5.setText(QtGui.QApplication.translate("mainWindow", "Save prefix:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.autosave_count = QtGui.QLineEdit(self.centralWidget)
        self.autosave_count.setGeometry(QtCore.QRect(130, 246, 141, 27))
        self.autosave_count.setText(_fromUtf8(""))
        self.autosave_count.setObjectName(_fromUtf8("autosave_count"))
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(56, 251, 71, 17))
        self.label_6.setText(QtGui.QApplication.translate("mainWindow", "Autosave:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(64, 289, 61, 17))
        self.label_7.setText(QtGui.QApplication.translate("mainWindow", "Monitor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.monitor_save = QtGui.QLineEdit(self.centralWidget)
        self.monitor_save.setGeometry(QtCore.QRect(130, 286, 61, 27))
        self.monitor_save.setText(_fromUtf8(""))
        self.monitor_save.setObjectName(_fromUtf8("monitor_save"))
        self.monitor_count = QtGui.QLineEdit(self.centralWidget)
        self.monitor_count.setGeometry(QtCore.QRect(210, 286, 61, 27))
        self.monitor_count.setText(_fromUtf8(""))
        self.monitor_count.setObjectName(_fromUtf8("monitor_count"))
        self.monitor_name = QtGui.QLineEdit(self.centralWidget)
        self.monitor_name.setGeometry(QtCore.QRect(130, 326, 141, 27))
        self.monitor_name.setText(_fromUtf8(""))
        self.monitor_name.setObjectName(_fromUtf8("monitor_name"))
        self.label_8 = QtGui.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(40, 330, 81, 17))
        self.label_8.setText(QtGui.QApplication.translate("mainWindow", "Monitor file:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.disconnect_button = QtGui.QPushButton(self.centralWidget)
        self.disconnect_button.setGeometry(QtCore.QRect(360, 30, 100, 27))
        self.disconnect_button.setText(QtGui.QApplication.translate("mainWindow", "Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.disconnect_button.setObjectName(_fromUtf8("disconnect_button"))
        self.start_button = QtGui.QPushButton(self.centralWidget)
        self.start_button.setGeometry(QtCore.QRect(330, 126, 131, 27))
        self.start_button.setText(QtGui.QApplication.translate("mainWindow", "Start measure", None, QtGui.QApplication.UnicodeUTF8))
        self.start_button.setObjectName(_fromUtf8("start_button"))
        self.stop_button = QtGui.QPushButton(self.centralWidget)
        self.stop_button.setGeometry(QtCore.QRect(330, 166, 131, 27))
        self.stop_button.setText(QtGui.QApplication.translate("mainWindow", "Stop measure", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_button.setObjectName(_fromUtf8("stop_button"))
        self.config_button = QtGui.QPushButton(self.centralWidget)
        self.config_button.setGeometry(QtCore.QRect(330, 86, 131, 27))
        self.config_button.setText(QtGui.QApplication.translate("mainWindow", "Send config", None, QtGui.QApplication.UnicodeUTF8))
        self.config_button.setObjectName(_fromUtf8("config_button"))
        self.command_log = QtGui.QPlainTextEdit(self.centralWidget)
        self.command_log.setGeometry(QtCore.QRect(50, 390, 461, 131))
        self.command_log.setObjectName(_fromUtf8("command_log"))
        self.server_port = QtGui.QLineEdit(self.centralWidget)
        self.server_port.setGeometry(QtCore.QRect(170, 30, 61, 27))
        self.server_port.setText(QtGui.QApplication.translate("mainWindow", "2606", None, QtGui.QApplication.UnicodeUTF8))
        self.server_port.setFrame(True)
        self.server_port.setObjectName(_fromUtf8("server_port"))
        self.label_9 = QtGui.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(170, 10, 67, 17))
        self.label_9.setText(QtGui.QApplication.translate("mainWindow", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(300, 220, 91, 17))
        self.label_10.setText(QtGui.QApplication.translate("mainWindow", "Server status:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.status_label = QtGui.QLineEdit(self.centralWidget)
        self.status_label.setGeometry(QtCore.QRect(400, 215, 113, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.status_label.setFont(font)
        self.status_label.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.status_label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.status_label.setAcceptDrops(False)
        self.status_label.setReadOnly(True)
        self.status_label.setObjectName(_fromUtf8("status_label"))
        self.label_11 = QtGui.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(340, 255, 61, 17))
        self.label_11.setText(QtGui.QApplication.translate("mainWindow", "Agents:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.agents_addresses = QtGui.QPlainTextEdit(self.centralWidget)
        self.agents_addresses.setGeometry(QtCore.QRect(300, 280, 211, 78))
        self.agents_addresses.setObjectName(_fromUtf8("agents_addresses"))
        self.agents_num = QtGui.QLineEdit(self.centralWidget)
        self.agents_num.setGeometry(QtCore.QRect(400, 250, 113, 27))
        self.agents_num.setObjectName(_fromUtf8("agents_num"))
        mainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        pass


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    mainWindow = QtGui.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

